Node modules ignore
ita-social-projects/Car-Front-End pull request #157
Opened 2021-02-14 21:44 UTC by Reennon

Restore gitignore
removed node_modules

2021-02-14 21:49 UTC, strelovidniy requested changes
Add node_modules folder to pull request

2021-02-15 11:24 UTC, AntonukOM commented
> Add node_modules folder to pull request

I believe we don't need that folder in the source code

2021-02-15 11:24 UTC, AntonukOM approved these changes

2021-02-15 12:38 UTC, RamzesUAA approved these changes

2021-02-15 12:46 UTC, NazariyChetvertukha approved these changes

2021-02-15 12:47 UTC, merged