Fix name of address added from "Address book"
ita-social-projects/Car-Front-End pull request #498
Opened 2021-07-28 06:05 UTC by shteniovych7

2021-07-28 07:02 UTC, EdgeOfMordor reviewed
Fix Code Smells

2021-07-28 07:08 UTC, vladzavorotny approved these changes

2021-07-29 08:10 UTC, strelovidniy requested changes
Remove Code Smells (you can find it on sonarscan analysis)

2021-08-02 06:51 UTC, EdgeOfMordor approved these changes

2021-08-02 13:58 UTC, strelovidniy approved these changes

2021-08-02 14:01 UTC, merged