More options list
ita-social-projects/Car-Front-End pull request #63
Opened 2021-01-21 21:24 UTC by RamzesUAA

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-21 21:31 UTC, TetianaLysak approved these changes

2021-01-22 08:41 UTC, AntonukOM requested changes

2021-01-22 08:41 UTC, AntonukOM commented on SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/JourneyPage.tsx
> +    if (props.isOpen == true) {
please simplify this code: init snap to value in the variable and use ternary operator for it, ex:
let index = props.isOpen ? 1 : 0;
myRef?.current?.snapTo(index )

2021-01-22 08:41 UTC, AntonukOM commented on SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/JourneyPage.tsx
> +
extra line

2021-01-22 08:41 UTC, AntonukOM commented on SoftServeCarMobile/src/activity/journey/more-options/JourneyPageMoreOptions.tsx
> +// import React from 'react';
please add todo with an explanation why code is comented

2021-01-22 08:41 UTC, AntonukOM commented on SoftServeCarMobile/src/components/bottom-popup/MenuButton.tsx
> +
please remove extra lines

2021-01-22 20:19 UTC, nrevutska reviewed
There are 3 code smells in your PR: [https://sonarcloud.io/project/issues?id=ita-social-projects_Car-Front-End&pullRequest=63&resolved=false&types=CODE_SMELL]()
Please, pay attention to these analysis  results

2021-01-25 18:35 UTC, closed without merging