Fixed bug where ''Apply changes'' and ''Discard changes" buttons  positions were incorrect
ita-social-projects/Car-Front-End pull request #723
Opened 2021-11-25 21:34 UTC by OleksandrHnidets

Fixed ita-social-projects/Car-Back-End/issues/889

2021-11-25 22:33 UTC, stasgut requested changes
![img](https://i.ibb.co/xjWvYR0/Screenshot-1637879633.png)
Wrong intend between buttons

2021-11-29 17:35 UTC, Hennadii-Sapryka approved these changes

2021-12-02 22:19 UTC, MedytskyiOleksandr approved these changes

2021-12-06 12:54 UTC, MaksymLazarev approved these changes

2021-12-17 13:52 UTC, stasgut reviewed
![img](https://ibb.co/dBYkRC4)

2022-01-05 12:58 UTC, closed without merging