Done#1015 Added badges photos and badges objects #1015
ita-social-projects/Car-Front-End pull request #834
Opened 2022-02-03 14:05 UTC by victoriamatush

/issues/1002
/issues/956

2022-02-03 16:19 UTC, MaksymTertychnyj approved these changes

2022-02-03 16:49 UTC, Waldemier requested changes
Please, change names of images, and create an enum type for badges.

2022-02-03 22:35 UTC, Pumpumpumbrr approved these changes

2022-02-03 22:36 UTC, VitaliiOryshchyn approved these changes

2022-02-03 22:38 UTC, RomanVynarovych approved these changes

2022-02-04 07:29 UTC, Waldemier approved these changes

2022-02-04 07:29 UTC, Waldemier commented on Car/src/components/badge/BadgeObjects.tsx
> +        isAchived: false
Rename it please to IsReached. I think it will be better. And add enum type of those badges

2022-02-04 07:56 UTC, merged